db_clients:
  - name: default
    rdbms: mysql
    host: 127.0.0.1
    port: 3306
    dbname: sentiment_analysis
    user: root
    passwd: "123456"
    is_fast: false
    number_of_connections: 1
    timeout: -1.0
    auto_batch: false

